FROM node:18-alpine   

WORKDIR /app

COPY package*.json ./  

RUN npm install 

COPY . . 

EXPOSE 3000

CMD ["node", "server.js"]



FROM node:18-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:18-alpine
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD ["node", "server.js"]

